apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docspell.fullname" . }}-restserver-secret
  labels:
    {{- include "restserver.labels" . | nindent 4 }}
type: Opaque
stringData:
    assertions:
      {{- if and (gt .Values.restserver.replicaCount 1.0) (not .Values.docspell.server.auth.serverSecret) -}}
      {{- fail "If multiple replicas are running of the rest server, the server secret has to be fixed." -}}
      {{- end -}}
      {{- if and (eq .Values.docspell.server.backend.signup.mode "invite") (not .Values.docspell.server.backend.signup.newInvitePassword) -}}
      {{- fail "Invite password has to be set, when using signup mode 'invite'" -}}
      {{- end -}}
    {{- include "docspell.server.secrets.auth" . | nindent 4 }}
    {{- include "docspell.server.secrets.openid" . | nindent 4 }}
    {{- include "docspell.server.secrets.integrationEndpoint" . | nindent 4 }}
    {{- include "docspell.server.secrets.adminEndpoint" . | nindent 4 }}
    {{- include "docspell.secrets.JDBC" (dict "context" . "type" "server") | nindent 4 -}}
    {{- include "docspell.server.secrets.signup" . | nindent 4 -}}